### ISSUE TITLE
Saving brain fire error : cannot serialize '_io.TextIOWrapper' object

### ISSUE THREAD

**Issue by ohoachuck** [keiffster/program-y#115]
## Expected Behavior
Save constructed brain to /tmp/y-bot.brain (while proper config.yaml parameters are set)

## Current Behavior
Crash at saving stage with the following stack:
`(program-y-3.6) oho ~/mypath/program-y/bots/titine $ ./y-bot.sh 

Loading, please wait...
No bot root argument set, defaulting to [.]
Traceback (most recent call last):
  File "../../src/programy/clients/console.py", line 90, in <module>
    run()
  File "../../src/programy/clients/console.py", line 87, in run
    console_app = ConsoleBotClient()
  File "../../src/programy/clients/console.py", line 28, in __init__
    BotClient.__init__(self, "Console", argument_parser)
  File "/mypath/program-y/src/programy/clients/client.py", line 48, in __init__
    self.create_brain()
  File "/mypath/program-y/src/programy/clients/client.py", line 65, in create_brain
    self._brain = Brain(self.configuration.brain_configuration)
  File "/mypath/program-y/src/programy/brain.py", line 74, in __init__
    self.load(self._configuration)
  File "/mypath/program-y/src/programy/brain.py", line 205, in load
    self.save_binary(brain_configuration)
  File "/mypath/program-y/src/programy/brain.py", line 188, in save_binary
    pickle.dump(self._aiml_parser, bin_file)
TypeError: cannot serialize '_io.TextIOWrapper' object
`
Last log message says : 
`2018-01-09 09:49:11,629  root       INFO    Saving binary brain to [/tmp/y-bot.brain]`

## Possible Solution
No idea ;(

## Steps to Reproduce
1. configure config.yaml like bellow:
`# Binary
     binaries:
       save_binary: true
       load_binary: false
       binary_filename: /tmp/y-bot.brain
       load_aiml_on_binary_fail: true`
2. launch y-bot.sh

## Context (Environment)
* Version of Y-Bot: App: v1.5.0 Grammar v1.5.0
* Version of Python: python 3.6
* Operating System ( inc Version ): mac OS (also verified on Linux Centos)

## Detailed Description
I don't know if I have changed something in my config that bing the issue and can't even remember if  it ever worked once. Sorry.

**Comment by keiffster** [comment]
Found it, introduced a file writer for something without ensuring that it was excluded from pickle

Just set the value to false for now and i'll issue a fix shortly

K

**Comment by keiffster** [comment]
Now fixed, tested and pushed to master

**Comment by ohoachuck** [comment]
thanx

**Comment by ohoachuck** [comment]
Hum, I still have an error :
```
Loading, please wait...
No bot root argument set, defaulting to [.]
Traceback (most recent call last):
  File "../../src/programy/clients/webchat/chatsrv.py", line 26, in <module>
    WEBCHAT_CLIENT = WebChatBotClient()
  File "../../src/programy/clients/webchat/chatsrv.py", line 17, in __init__
    BotClient.__init__(self, "WebChat")
  File "/mypath/program-y/src/programy/clients/client.py", line 48, in __init__
    self.create_brain()
  File "/mypath/program-y/src/programy/clients/client.py", line 65, in create_brain
    self._brain = Brain(self.configuration.brain_configuration)
  File "/mypath/program-y/src/programy/brain.py", line 74, in __init__
    self.load(self._configuration)
  File "/mypath/program-y/src/programy/brain.py", line 205, in load
    self.save_binary(brain_configuration)
  File "/mypath/program-y/src/programy/brain.py", line 188, in save_binary
    pickle.dump(self._aiml_parser, bin_file)
  File "/mypath/program-y/src/programy/parser/aiml_parser.py", line 64, in __getstate__
    del d['_errors']
KeyError: '_errors'```

**Comment by keiffster** [comment]
My fault, pushed the fix to early and didn't check for existance of attributes in class before deleting.
Just pushed a fix to master

**Comment by ohoachuck** [comment]
Cool, it's working now. 👍
