### ISSUE TITLE
Calling REST Client API fire a crash

### ISSUE THREAD

**Issue by ohoachuck** [keiffster/program-y#144]
## Expected Behavior
Use REST client launched with ```./y-bot-flask-rest.sh``` does not crash.

## Current Behavior
While using REST client, calling the API with:
```http://0.0.0.0:8989/api/rest/v1.0/ask?question=my+question&sessionid=123456789``` 
or even with:
```http://0.0.0.0:8989/api/rest/v1.0/ask?question=my+question&userid=123456789``` 
does fire a crash:

```log
Traceback (most recent call last):
  File "/home/oho/.virtualenvs/program-y/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/oho/.virtualenvs/program-y/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/oho/.virtualenvs/program-y/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/oho/.virtualenvs/program-y/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/oho/.virtualenvs/program-y/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/oho/.virtualenvs/program-y/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/oho/.virtualenvs/program-y/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/oho/.virtualenvs/program-y/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/oho/.virtualenvs/program-y/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/oho/.virtualenvs/program-y/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/web/program-y/src/programy/clients/restful/flask/client.py", line 109, in ask
    return REST_CLIENT.create_response(request, status)
  File "/home/web/program-y/src/programy/clients/restful/flask/client.py", line 65, in create_response
    return make_response(jsonify({'response': response}, status))
  File "/home/oho/.virtualenvs/program-y/lib/python3.6/site-packages/flask/json.py", line 263, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "/home/oho/.virtualenvs/program-y/lib/python3.6/site-packages/flask/json.py", line 123, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/local/lib/python3.6/json/encoder.py", line 428, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/local/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/local/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/home/oho/.virtualenvs/program-y/lib/python3.6/site-packages/flask/json.py", line 80, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'LocalProxy' is not JSON serializable


```
## Possible Solution
Link with Redis ?

## Steps to Reproduce
```http://0.0.0.0:8989/api/rest/v1.0/ask?question=my+question&userid=123456789``` 
or 
```http://0.0.0.0:8989/api/rest/v1.0/ask?question=my+question&sessionid=123456789``` 

## Context (Environment)

* Version of Y-Bot: latest 2.0 RC1
* Version of Python: 3.6
* Operating System ( inc Version ): Centos 7.3

**Comment by keiffster** [comment]
Fixed and pushed to master

**Comment by ohoachuck** [comment]
Thanx.
Working like a charm.
O.
