### ISSUE TITLE
Unable to pip install from `v3`

### ISSUE THREAD

**Issue by elcolie** [keiffster/program-y#171]
```bash
(y-bot) KrungThep:y-bot sarit$ pip install -e git+git@github.com:keiffster/program-y.git@v3#egg=programy
Obtaining programy from git+git@github.com:keiffster/program-y.git@v3#egg=programy
  Updating /Users/sarit/.pyenv/versions/3.7.0/envs/y-bot/src/programy clone (to revision v3)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/sarit/.pyenv/versions/3.7.0/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarit/.pyenv/versions/3.7.0/envs/y-bot/src/programy/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/sarit/.pyenv/versions/3.7.0/envs/y-bot/src/programy/
```

Could you please put `setup.py` to fix this?

**Comment by keiffster** [comment]
V3 is not ready for a pip install. Only way is to clone the Repo in git or download a zip of the Repo

I’ll have documentation for the new work in a few days

**Comment by keiffster** [comment]
Now fixed in v3 and just pushed to pypi
