### ISSUE TITLE
No module named 'pip.req'

### ISSUE THREAD

**Issue by xuexiaoao** [keiffster/program-y#182]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE ACCEPTED! Use [stackoverflow](https://stackoverflow.com) for supporting issues.

## Expected Behavior

use pip install programy on windows
## Current Behavior

Report an error
```shell
Requirement already satisfied: requests==2.20.0 in c:\users\xuexi\appdata\local\programs\python\python36\lib\site-packages (from programy) (2.20.0)
Requirement already satisfied: Flask==1.0.2 in c:\users\xuexi\appdata\local\programs\python\python36\lib\site-packages (from programy) (1.0.2)
Collecting Flask-Ask==0.9.8 (from programy)
  Using cached https://files.pythonhosted.org/packages/6a/f5/d4709ae94584a0b1541e9b52b2d25a8a1bdb6e2da9d6870f23fdd0523a30/Flask-Ask-0.9.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xuexi\AppData\Local\Temp\pip-install-mykj8aab\Flask-Ask\setup.py", line 8, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\xuexi\AppData\Local\Temp\pip-install-mykj8aab\Flask-Ask\
```
## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

* Version of Y-Bot:
* Version of Python: 3.6.6
* Operating System ( inc Version ):  windows 10

**Comment by keiffster** [comment]
Looks like Flask-Ask which is the framework I use for the Alexa client does not install on Windows. 

As a short term fix I will comment out the following line in requirements.txt as follows
```
#Flask-Ask==0.9.8
```
I've pushed a new version to PyPi with this fix in

**Comment by xuexiaoao** [comment]
thanks
