### ISSUE TITLE
Program-y should not crash on invalid AIML

### ISSUE THREAD

**Issue by JustArchi** [keiffster/program-y#23]
In my case, one of the AIML simply had mismatched `</li>content</li>` instead of one opening tag. This caused entire program-y to crash, I think it'd be the best if it simply ignored given node if it's unparsable.

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1654, in feed
    self.parser.Parse(data, 0)
xml.parsers.expat.ExpatError: mismatched tag: line 41, column 10

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../src/programy/clients/rest.py", line 34, in <module>
    rest_client = RestBotClient()
  File "../../src/programy/clients/rest.py", line 25, in __init__
    BotClient.__init__(self)
  File "/home/steam/ArchiBoT/program-y/src/programy/clients/clients.py", line 83, in __init__
    self.initiate_bot(self.configuration)
  File "/home/steam/ArchiBoT/program-y/src/programy/clients/clients.py", line 129, in initiate_bot
    self._brain = Brain(configuration.brain_configuration)
  File "/home/steam/ArchiBoT/program-y/src/programy/brain.py", line 58, in __init__
    self.load(self._configuration)
  File "/home/steam/ArchiBoT/program-y/src/programy/brain.py", line 121, in load
    self._aiml_parser.load_aiml(brain_configuration)
  File "/home/steam/ArchiBoT/program-y/src/programy/parser/aiml_parser.py", line 63, in load_aiml
    brain_configuration.aiml_files.extension)
  File "/home/steam/ArchiBoT/program-y/src/programy/utils/files/filefinder.py", line 57, in load_dir_contents
    collection[filename] = self.load_file_contents(file[1])
  File "/home/steam/ArchiBoT/program-y/src/programy/parser/aiml_parser.py", line 36, in load_file_contents
    return self.aiml_parser.parse_from_file(filename)
  File "/home/steam/ArchiBoT/program-y/src/programy/parser/aiml_parser.py", line 78, in parse_from_file
    tree = ET.parse(filename, parser=LineNumberingParser())
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1195, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 602, in parse
    parser.feed(data)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1656, in feed
    self._raiseerror(v)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1555, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: mismatched tag: line 41, column 10
```

**Comment by keiffster** [comment]
Good shout, I'll have a lot at wrapping the parsing with an try/catch clause, write an error out and throw away the impacting line

K

**Comment by keiffster** [comment]
Check out 0.6.0, no longer crashes in file contains invalid XML

Due to the  nature of the XML parser I use, I reject the whole file and report an error in the log

K

**Comment by Thielak** [comment]
> ERROR:root:Failed to load contents of AIML file from [./aiml/test.aiml] - [mismatched tag: line 9, column 6]

I can confirm it graciously handles the error without crashing, thank you.

**Comment by JustArchi** [comment]
Closing as it's solved now, lots of thanks Keiff! ❤️
