### ISSUE TITLE
UnicodeEncodeError on first run

### ISSUE THREAD

**Issue by afharvey** [keiffster/program-y#73]
I get a UnicodeEncodeError when running y-bot for the first time.

Here's a fix: https://github.com/afharvey/program-y/pull/1

I'm running 'Python 3.6.2' on Linux.

Here's how to recreate:
```
git clone repo
pip install -r requirements.txt
cd bots/y-bot
./y-bot.sh
```

This is the error:
```
$ ./y-bot.sh 

Loading, please wait...
No bot root argument set, defaulting to [.]
Traceback (most recent call last):
  File "../../src/programy/clients/console.py", line 73, in <module>
    run()
  File "../../src/programy/clients/console.py", line 70, in run
    console_app = ConsoleBotClient()
  File "../../src/programy/clients/console.py", line 25, in __init__
    BotClient.__init__(self, argument_parser)
  File "/home/alex/go/src/github.com/keiffster/program-y/src/programy/clients/client.py", line 36, in __init__
    self._brain = Brain(self.configuration.brain_configuration)
  File "/home/alex/go/src/github.com/keiffster/program-y/src/programy/brain.py", line 70, in __init__
    self.load(self._configuration)
  File "/home/alex/go/src/github.com/keiffster/program-y/src/programy/brain.py", line 183, in load
    self.load_aiml(brain_configuration)
  File "/home/alex/go/src/github.com/keiffster/program-y/src/programy/brain.py", line 166, in load_aiml
    self._aiml_parser.load_aiml(brain_configuration)
  File "/home/alex/go/src/github.com/keiffster/program-y/src/programy/parser/aiml_parser.py", line 134, in load_aiml
    self.pattern_parser.dump_to_file(brain_configuration.binaries.dump_to_file)
  File "/home/alex/go/src/github.com/keiffster/program-y/src/programy/parser/pattern/graph.py", line 240, in dump_to_file
    self.dump(output_func=dump_file.write, eol="\n")
  File "/home/alex/go/src/github.com/keiffster/program-y/src/programy/parser/pattern/graph.py", line 235, in dump
    self.root.dump("", output_func, eol, verbose)
  File "/home/alex/go/src/github.com/keiffster/program-y/src/programy/parser/pattern/nodes/base.py", line 383, in dump
    self._0ormore_hash.dump(tabs+"\t", output_func, eol, verbose)
  File "/home/alex/go/src/github.com/keiffster/program-y/src/programy/parser/pattern/nodes/base.py", line 396, in dump
    child.dump(tabs+"\t", output_func, eol, verbose)
  File "/home/alex/go/src/github.com/keiffster/program-y/src/programy/parser/pattern/nodes/base.py", line 383, in dump
    self._0ormore_hash.dump(tabs+"\t", output_func, eol, verbose)
  File "/home/alex/go/src/github.com/keiffster/program-y/src/programy/parser/pattern/nodes/base.py", line 396, in dump
    child.dump(tabs+"\t", output_func, eol, verbose)
  File "/home/alex/go/src/github.com/keiffster/program-y/src/programy/parser/pattern/nodes/base.py", line 396, in dump
    child.dump(tabs+"\t", output_func, eol, verbose)
  File "/home/alex/go/src/github.com/keiffster/program-y/src/programy/parser/pattern/nodes/base.py", line 389, in dump
    self._topic.dump(tabs+"\t", output_func, eol, verbose)
  File "/home/alex/go/src/github.com/keiffster/program-y/src/programy/parser/pattern/nodes/base.py", line 387, in dump
    self._1ormore_star.dump(tabs+"\t", output_func, eol, verbose)
  File "/home/alex/go/src/github.com/keiffster/program-y/src/programy/parser/pattern/nodes/base.py", line 391, in dump
    self._that.dump(tabs+"\t", output_func, eol, verbose)
  File "/home/alex/go/src/github.com/keiffster/program-y/src/programy/parser/pattern/nodes/base.py", line 387, in dump
    self._1ormore_star.dump(tabs+"\t", output_func, eol, verbose)
  File "/home/alex/go/src/github.com/keiffster/program-y/src/programy/parser/pattern/nodes/base.py", line 393, in dump
    self._template.dump(tabs+"\t", output_func, eol, verbose)
  File "/home/alex/go/src/github.com/keiffster/program-y/src/programy/parser/pattern/nodes/base.py", line 393, in dump
    self._template.dump(tabs+"\t", output_func, eol, verbose)
  File "/home/alex/go/src/github.com/keiffster/program-y/src/programy/parser/template/nodes/base.py", line 37, in dump
    self.output(tabs, output_func, eol, verbose)
  File "/home/alex/go/src/github.com/keiffster/program-y/src/programy/parser/template/nodes/base.py", line 40, in output
    self.output_child(self, tabs, eol, output_func)
  File "/home/alex/go/src/github.com/keiffster/program-y/src/programy/parser/template/nodes/base.py", line 44, in output_child
    output_func("%s{%s}%s" % (tabs, child.to_string(), eol))
UnicodeEncodeError: 'ascii' codec can't encode character '\xa3' in position 18: ordinal not in range(128)

```

**Comment by ideasean** [comment]
I've seen something similar happen if there are unicode characters in the full path.

**Comment by afharvey** [comment]
Maybe this helps:
```
$ python
Python 3.6.2 (default, Jul 20 2017, 03:52:27) 
[GCC 7.1.1 20170630] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/home/alex/.virtualenvs/program-y/lib/python36.zip', '/home/alex/.virtualenvs/program-y/lib/python3.6', '/home/alex/.virtualenvs/program-y/lib/python3.6/lib-dynload', '/usr/lib64/python3.6', '/usr/lib/python3.6', '/home/alex/.virtualenvs/program-y/lib/python3.6/site-packages']
```

**Comment by keiffster** [comment]
Thanks added the change to output_func in both template/nodes/base.py and parser/nodes/base.py

Just committed to master
